name: nova
description: Jarvis-style AI code assistant with voice (Hindi/English), built in Flutter.
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.1.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^0.13.5
  flutter_highlight: ^0.7.0
  path_provider: ^2.1.2
  speech_to_text: ^6.6.0
  flutter_tts: ^3.8.5
  archive: ^3.4.10

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true